
[bell]
animation = "EaseOutExpo"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[cursor]
unfocused_hollow = true
vi_mode_style = "Underline"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty-direct"

[font]
size = 12

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[font.italic]
family = "Hack"
style = "Italic"

[font.normal]
family = "Hack"
style = ""

[font.offset]
x = 0
y = 1

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"

[general]
live_config_reload = true

[terminal]
